services:
  web:
    build: .
    container_name: tool_warehouse
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8002
    ports:
      - "8002:8002"
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
    env_file:
      - .env
    restart: unless-stopped