# Generated by Django 6.0.2 on 2026-03-01 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomenclature', models.CharField(max_length=255, verbose_name='Номенклатура')),
                ('unit', models.CharField(max_length=10, verbose_name='Единица')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Количество')),
            ],
            options={
                'verbose_name': 'Склад инструмента',
                'verbose_name_plural': 'Склад инструментов',
            },
        ),
    ]
